// File generated by the K Framework Go backend. Timestamp: 2019-07-30 16:35:04.814

package ieletestinginterpreter

import (
	m "github.com/ElrondNetwork/elrond-vm/iele/original/standalone/iele-testing-kompiled/ieletestingmodel"
	krypto "github.com/ElrondNetwork/elrond-vm/iele/original/standalone/hookadapter/krypto"
)

// Interpreter is a container with a reference to model and basic options
type Interpreter struct {
	Model         *m.ModelState
	currentStep   int
	MaxSteps      int
	state         m.KReference
	traceHandlers []traceHandler
	Verbose       bool

	kryptoRef *krypto.Krypto
}
// NewInterpreter creates a new interpreter instance
func NewInterpreter(kryptoRef *krypto.Krypto) *Interpreter {

	return &Interpreter {
		Model:         m.NewModel(),
		MaxSteps:      0,
		currentStep:   -1, // meaning that no processing started yet
		state:         m.NullReference,
		traceHandlers: nil,
		Verbose:       false,
		kryptoRef: kryptoRef,
	}
}
